### ISSUE TITLE
Error when trying to load plugin

### ISSUE THREAD

**Issue by KaoticOblivion** [jaimeadf/who-reacted#4]
Hi! I've been getting this error as of this morning when using Discord. I've tried restarting and un/reinstalling it as well.

Error:
TypeError: Cannot read property 'children' of undefined
    at n.props.children (Who Reacted | GM Module:40:5988)

**Comment by ItzDragonFace** [comment]
Hello! I have gone ahead and made a pull request for this issue, + Version Bump!
Hope this helps!
~ Dragon ~

**Comment by KaoticOblivion** [comment]
hope so!
